name: forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - altair=5.4.1
  - altair-all=5.4.1
  - altair_tiles=0.3.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=16.1.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.3
  - fontconfig=2.14.1
  - freetype=2.12.1
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.27.0
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.9.1
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.1.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libuuid=1.41.5
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.1
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.6
  - mercantile=1.2.1
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mysql=5.7.24
  - narwhals=1.8.1
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.3.2
  - orc=2.0.1
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.25.3
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pybind11-abi=4
  - pycparser=2.21
  - pygments=2.15.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - s2n=1.3.27
  - scikit-base=0.8.2
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - send2trash=1.8.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sktime=0.32.4
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - tbb=2021.8.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - vegafusion=1.6.9
  - vegafusion-python-embed=1.6.9
  - vl-convert-python=1.6.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.10
  - xyzservices=2024.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.5
