name: forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=gpu_0
  - aiohappyeyeballs=2.4.0=py310h06a4308_0
  - aiohttp=3.10.5=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alembic=1.8.1=py310h06a4308_0
  - altair=5.4.1=pyhd8ed1ab_0
  - altair-all=5.4.1=pyhd8ed1ab_0
  - altair_tiles=0.3.0=pyhd8ed1ab_0
  - aniso8601=9.0.1=pyhd3eb1b0_0
  - anyio=4.2.0=py310h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py310h06a4308_0
  - async-timeout=4.0.3=py310h06a4308_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hff2c3d7_3
  - aws-c-common=0.8.5=h166bdaf_0
  - aws-c-compression=0.2.16=hf5f93bc_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h2666983_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=hf5f93bc_1
  - aws-checksums=0.1.13=hf5f93bc_5
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - babel=2.11.0=py310h06a4308_0
  - bcrypt=3.2.0=py310h5eee18b_1
  - beautifulsoup4=4.12.3=py310h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py310h06a4308_0
  - blosc=1.21.3=h6a678d5_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py310ha9d4c09_0
  - branca=0.6.0=py310h06a4308_0
  - brotli=1.0.9=he6710b0_2
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2024.9.24=h06a4308_0
  - cachetools=5.3.3=py310h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.8.30=py310h06a4308_0
  - cffi=1.16.0=py310h5eee18b_1
  - cfitsio=3.470=h5893167_7
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - cloudpickle=3.0.0=py310h06a4308_0
  - colorama=0.4.6=py310h06a4308_0
  - comm=0.2.1=py310h06a4308_0
  - contourpy=1.2.0=py310hdb19cb5_0
  - cryptography=43.0.0=py310hdda0065_0
  - cuda-version=11.8=hcce14f8_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - databricks-sdk=0.32.1=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py310h06a4308_0
  - docker-py=7.0.0=py310h06a4308_0
  - entrypoints=0.4=py310h06a4308_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - fiona=1.9.5=py310h1128e8f_0
  - flask=3.0.3=py310h06a4308_0
  - folium=0.14.0=py310h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py310h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - freexl=2.0.0=hf309648_0
  - frozenlist=1.4.0=py310h5eee18b_0
  - gdal=3.6.2=py310h0daa840_5
  - geopandas=0.14.2=py310h06a4308_0
  - geopandas-base=0.14.2=py310h06a4308_0
  - geos=3.8.0=he6710b0_0
  - geotiff=1.7.0=h2a26cda_3
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py310h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h48cff8f_0
  - google-auth=2.29.0=py310h06a4308_0
  - graphene=3.3=py310h06a4308_0
  - graphql-core=3.2.3=py310h06a4308_1
  - graphql-relay=3.2.0=py310h06a4308_0
  - greenlet=3.0.1=py310h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gunicorn=22.0.0=py310h06a4308_0
  - h11=0.14.0=py310h06a4308_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - httpcore=1.0.2=py310h06a4308_0
  - httpx=0.27.0=py310h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.28.0=py310h06a4308_0
  - ipython=8.27.0=py310h06a4308_0
  - ipywidgets=8.1.2=py310h06a4308_0
  - itsdangerous=2.2.0=py310h06a4308_0
  - jedi=0.19.1=py310h06a4308_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json-c=0.16=h5eee18b_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter=1.0.0=py310h06a4308_9
  - jupyter-lsp=2.2.0=py310h06a4308_0
  - jupyter_client=8.6.0=py310h06a4308_0
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.7.2=py310h06a4308_0
  - jupyter_events=0.10.0=py310h06a4308_0
  - jupyter_server=2.14.1=py310h06a4308_0
  - jupyter_server_terminals=0.4.4=py310h06a4308_1
  - jupyterlab=4.2.5=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py310h06a4308_0
  - jupyterlab_widgets=3.0.10=py310h06a4308_0
  - kealib=1.5.0=hd940352_1
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgdal=3.6.2=hd4d5da2_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.1.0=h77fa898_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libkml=1.3.0=h096b73e_7
  - libllvm14=14.0.6=hdb19cb5_3
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libspatialite=5.1.0=h040243e_1
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxgboost=2.1.1=cuda118_h09a87be_4
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - libzip=1.8.0=h6ac8c49_1
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.2.3=py310h06a4308_0
  - mapclassify=2.5.0=py310h06a4308_0
  - markdown=3.4.1=py310h06a4308_0
  - markupsafe=2.1.5=py310ha75aee5_1
  - matplotlib-base=3.9.2=py310hbfdbfaf_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - minizip=4.0.3=hf59b114_0
  - mistune=2.0.4=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mlflow=2.16.2=hff52083_0
  - mlflow-skinny=2.16.2=py310hff52083_0
  - mlflow-ui=2.16.2=py310hff52083_0
  - multidict=6.0.4=py310h5eee18b_0
  - mysql=5.7.24=h721c034_2
  - narwhals=1.8.1=pyhd8ed1ab_0
  - nbclient=0.8.0=py310h06a4308_0
  - nbconvert=7.10.0=py310h06a4308_0
  - nbformat=5.9.2=py310h06a4308_0
  - nccl=2.23.4.1=h03a54cd_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - networkx=3.3=py310h06a4308_0
  - notebook=7.2.2=py310h06a4308_0
  - notebook-shim=0.2.3=py310h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - opentelemetry-api=1.16.0=pyhd8ed1ab_0
  - opentelemetry-sdk=1.16.0=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.37b0=pyhd8ed1ab_0
  - orc=2.0.1=h2d29ad5_0
  - overrides=7.4.0=py310h06a4308_0
  - packaging=24.1=py310h06a4308_0
  - pandas=2.2.2=py310h6a678d5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.6=py310h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.10.0=py310h06a4308_0
  - plotly=5.24.1=pyhd8ed1ab_0
  - ply=3.11=py310h06a4308_0
  - poppler=22.12.0=h9614445_3
  - poppler-data=0.4.11=h06a4308_1
  - proj=9.3.1=he5811b7_0
  - prometheus_client=0.14.1=py310h06a4308_0
  - prometheus_flask_exporter=0.22.4=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.25.3=py310h0e2eeba_1
  - psutil=6.0.0=py310ha75aee5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.1.1=cuda118_pyh40095f8_4
  - pyarrow=16.1.0=py310h1128e8f_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pynacl=1.5.0=py310h5eee18b_0
  - pyopenssl=24.2.1=py310h06a4308_0
  - pyparsing=3.1.2=py310h06a4308_0
  - pyproj=3.6.1=py310h6370d16_0
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.16.2=py310h06a4308_0
  - python-json-logger=2.0.7=py310h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - qhull=2020.2=hdb19cb5_2
  - qt-main=5.15.2=h53bd1ea_10
  - qtconsole=5.5.1=py310h06a4308_0
  - qtpy=2.4.1=py310h06a4308_0
  - querystring_parser=1.2.4=py310h06a4308_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=py310h06a4308_0
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.20.0=py310h505e2c1_1
  - rsa=4.7.2=pyhd3eb1b0_1
  - rtree=1.0.1=py310h06a4308_0
  - s2n=1.3.27=h1b5e8cb_0
  - scikit-learn=1.5.1=py310h1128e8f_0
  - scipy=1.13.1=py310h5f9d8c6_0
  - send2trash=1.8.2=py310h06a4308_0
  - setuptools=72.1.0=py310h06a4308_0
  - shapely=2.0.5=py310h006c72b_0
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlalchemy=2.0.34=py310h00e1ef3_0
  - sqlite=3.45.3=h5eee18b_0
  - sqlparse=0.4.4=py310h06a4308_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.2=py310h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.3=py310h06a4308_0
  - terminado=0.17.1=py310h06a4308_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tiledb=2.3.3=h77177df_3
  - tinycss2=1.2.1=py310h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.4.1=py310h5eee18b_0
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py310h5eee18b_0
  - uriparser=0.9.7=h5eee18b_0
  - urllib3=2.2.2=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - vegafusion=1.6.9=pyhd8ed1ab_0
  - vegafusion-python-embed=1.6.9=py310he421c4c_0
  - vl-convert-python=1.6.1=py310ha75aee5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - werkzeug=3.0.3=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - widgetsnbextension=4.0.10=py310h06a4308_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xerces-c=3.2.4=h6a678d5_1
  - xgboost=2.1.1=cuda118_pyh256f914_4
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.11.0=py310h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - colorlog==6.8.2
      - optuna==4.0.0
      - skforecast==0.13.0
prefix: /home/luismg0203/miniconda3/envs/forecasting
